# Generated by Django 5.0.1 on 2024-01-31 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_student_teacher'),
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='题目内容')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='考试标题')),
                ('description', models.TextField(verbose_name='考试描述')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('students', models.ManyToManyField(blank=True, to='student_app.student', verbose_name='参与考试的学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.teacher', verbose_name='教师')),
                ('questions', models.ManyToManyField(blank=True, to='teacher_app.examquestion', verbose_name='考试题目')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='练习题标题')),
                ('content', models.TextField(verbose_name='练习题内容')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.teacher', verbose_name='发布教师')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.exercise', verbose_name='练习')),
            ],
        ),
    ]
