# Generated by Django 5.0.1 on 2024-02-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0003_teacher_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='userid',
        ),
    ]
