# Generated by Django 5.0.1 on 2024-02-11 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_remove_student_class_num_remove_student_gender_and_more'),
        ('teacher_app', '0004_rename_teacher_id_teacher_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='班级名称')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('students', models.ManyToManyField(blank=True, to='student_app.student', verbose_name='接收公告的学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.teacher', verbose_name='发布教师')),
                ('class_to_notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.class', verbose_name='接收公告的班级')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes_assigned',
            field=models.ManyToManyField(blank=True, to='teacher_app.class', verbose_name='所教班级'),
        ),
    ]
