# Generated by Django 5.0.1 on 2024-02-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0006_rename_description_exam_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_num',
            field=models.CharField(max_length=12, null=True, verbose_name='电话号码'),
        ),
    ]
