# Generated by Django 5.0.1 on 2024-02-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(to='teacher_app.class', verbose_name='接收班级'),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
