# Generated by Django 5.0.1 on 2024-02-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0010_exercisequestion_memory_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='cotitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='题目标题'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='memory_limit',
            field=models.IntegerField(default=0, verbose_name='内存限制'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='time_limit',
            field=models.IntegerField(default=0, verbose_name='时间限制'),
        ),
    ]
