# Generated by Django 5.0.1 on 2024-02-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0011_examquestion_cotitle_examquestion_memory_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='cotitle',
            new_name='title',
        ),
    ]
