# Generated by Django 5.0.1 on 2024-02-20 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0013_alter_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_app.teacher', verbose_name='发布教师'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_app.teacher', verbose_name='发布教师'),
        ),
    ]
