# Generated by Django 5.0.1 on 2024-02-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0014_alter_exam_teacher_alter_exercise_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='通知标题'),
        ),
    ]
