# Generated by Django 5.0.1 on 2024-02-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0015_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='答案'),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='答案'),
        ),
    ]
