# Generated by Django 5.0.1 on 2024-03-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0016_examquestion_answer_exercisequestion_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalscore', models.IntegerField(verbose_name='总分')),
                ('contents', models.IntegerField(verbose_name='内容得分')),
                ('firstrow', models.IntegerField(verbose_name='首行得分')),
                ('fontsize', models.IntegerField(verbose_name='字体大小得分')),
                ('image', models.IntegerField(verbose_name='图片得分')),
                ('pagenum', models.IntegerField(verbose_name='页数得分')),
                ('titlestyle', models.IntegerField(verbose_name='标题风格得分')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_scores', to='teacher_app.teacher', verbose_name='教师')),
            ],
        ),
    ]
