# Generated by Django 5.0.1 on 2024-03-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0018_remove_reportscore_titlestyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
