# Generated by Django 5.0.1 on 2024-01-31 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CodeBERT_app', '0001_initial'),
        ('student_app', '0003_student_teacher'),
        ('teacher_app', '0002_examquestion_exam_exercise_exercisequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_app.exam', verbose_name='考试'),
        ),
        migrations.AddField(
            model_name='score',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_app.exercise', verbose_name='练习'),
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student', verbose_name='学生'),
        ),
    ]
