# Generated by Django 5.0.1 on 2024-02-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBERT_app', '0003_codefeature_delete_score'),
        ('administrator_app', '0010_programmingexercise'),
        ('student_app', '0019_examcompletion_examquestioncompletion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingCodeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(verbose_name='特征值')),
                ('programming_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programming_code_features', to='administrator_app.programmingexercise', verbose_name='练习题')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programming_code_features', to='student_app.student', verbose_name='学生')),
            ],
        ),
    ]
