# Generated by Django 5.0.1 on 2024-03-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBERT_app', '0004_programmingcodefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingcodefeature',
            name='cosine_similarity',
            field=models.FloatField(blank=True, null=True, verbose_name='余弦相似度'),
        ),
    ]
