# Generated by Django 5.0.1 on 2024-03-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBERT_app', '0005_programmingcodefeature_cosine_similarity'),
        ('administrator_app', '0011_alter_programmingexercise_posted_by'),
        ('student_app', '0019_examcompletion_examquestioncompletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingcodefeature',
            name='similar_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_code_students', to='student_app.student', verbose_name='相似的学生用户'),
        ),
        migrations.CreateModel(
            name='ProgrammingReportFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(verbose_name='特征值')),
                ('cosine_similarity', models.FloatField(blank=True, null=True, verbose_name='余弦相似度')),
                ('programming_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programming_report_features', to='administrator_app.programmingexercise', verbose_name='练习题')),
                ('similar_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_report_students', to='student_app.student', verbose_name='相似的学生用户')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programming_report_features', to='student_app.student', verbose_name='学生')),
            ],
        ),
    ]
