# Generated by Django 5.0.1 on 2024-03-15 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBERT_app', '0007_reportstandardscore'),
        ('administrator_app', '0011_alter_programmingexercise_posted_by'),
        ('student_app', '0019_examcompletion_examquestioncompletion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeStandardScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_score', models.IntegerField(default=0, verbose_name='规范性得分')),
                ('programming_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_standards', to='administrator_app.programmingexercise', verbose_name='编程题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_standards', to='student_app.student', verbose_name='学生')),
            ],
        ),
    ]
