# Generated by Django 5.0.1 on 2024-03-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBERT_app', '0008_codestandardscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codestandardscore',
            name='standard_score',
            field=models.IntegerField(default=0, verbose_name='代码规范性得分'),
        ),
        migrations.AlterField(
            model_name='reportstandardscore',
            name='standard_score',
            field=models.IntegerField(verbose_name='报告规范性得分'),
        ),
    ]
