# Generated by Django 5.0.1 on 2024-03-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBERT_app', '0009_alter_codestandardscore_standard_score_and_more'),
        ('administrator_app', '0012_alter_administrator_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='codestandardscore',
            name='file_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='代码文件路径'),
        ),
        migrations.AlterField(
            model_name='codestandardscore',
            name='programming_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_standards', to='administrator_app.programmingexercise', verbose_name='练习题'),
        ),
    ]
