# Generated by Django 5.0.1 on 2024-03-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBERT_app', '0010_codestandardscore_file_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeFeature',
        ),
    ]
