# Generated by Django 5.0.1 on 2024-04-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBERT_app', '0011_delete_codefeature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeStandardScore',
        ),
    ]
