# Generated by Django 5.0.1 on 2024-02-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='teacher_id',
            new_name='admin_id',
        ),
    ]
