# Generated by Django 5.0.1 on 2024-02-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0004_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间'),
        ),
    ]
