# Generated by Django 5.0.1 on 2024-02-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0005_administrator_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='admin_id',
            new_name='userid',
        ),
    ]
