# Generated by Django 5.0.1 on 2024-02-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0006_rename_admin_id_administrator_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='phone_num',
            field=models.CharField(max_length=12, null=True, verbose_name='电话号码'),
        ),
    ]
