# Generated by Django 5.0.1 on 2024-02-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0007_alter_administrator_phone_num'),
        ('teacher_app', '0016_examquestion_answer_exercisequestion_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('recipients', models.ManyToManyField(to='teacher_app.teacher', verbose_name='接收教师')),
            ],
        ),
    ]
