# Generated by Django 5.0.1 on 2024-02-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0009_remove_adminnotification_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='题目标题')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.administrator', verbose_name='发布者')),
            ],
        ),
    ]
