# Generated by Django 5.0.1 on 2024-03-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0012_alter_administrator_password'),
        ('teacher_app', '0019_alter_teacher_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='考试标题')),
                ('content', models.TextField(verbose_name='考试描述')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('classes', models.ManyToManyField(blank=True, to='teacher_app.class', verbose_name='参与考试的班级')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator_app.administrator', verbose_name='发布教师')),
            ],
        ),
        migrations.CreateModel(
            name='AdminExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('memory_limit', models.IntegerField(default=0, verbose_name='内存限制')),
                ('time_limit', models.IntegerField(default=0, verbose_name='时间限制')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='答案')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='administrator_app.adminexam', verbose_name='考试')),
            ],
        ),
    ]
