# Generated by Django 5.0.1 on 2024-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0013_adminexam_adminexamquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
