# Generated by Django 5.0.1 on 2024-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0014_alter_administrator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登录时间'),
        ),
    ]
