# Generated by Django 5.0.1 on 2024-02-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
