# Generated by Django 5.0.1 on 2024-02-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_remove_student_teacher'),
        ('teacher_app', '0002_examquestion_exam_exercise_exercisequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_app.teacher', verbose_name='教师'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
