# Generated by Django 5.0.1 on 2024-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_student_teacher_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间'),
        ),
    ]
