# Generated by Django 5.0.1 on 2024-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_student_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
    ]
