# Generated by Django 5.0.1 on 2024-02-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_rename_student_id_student_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_num',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
