# Generated by Django 5.0.1 on 2024-02-11 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_remove_student_class_num_remove_student_gender_and_more'),
        ('teacher_app', '0005_class_remove_teacher_gender_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_app.class', verbose_name='班级'),
        ),
    ]
