# Generated by Django 5.0.1 on 2024-02-16 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0014_alter_student_class_assigned'),
        ('teacher_app', '0007_alter_teacher_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='teacher_app.class', verbose_name='班级'),
        ),
    ]
