# Generated by Django 5.0.1 on 2024-02-19 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0015_alter_student_class_assigned'),
        ('teacher_app', '0012_rename_cotitle_examquestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teacher_app.class', verbose_name='班级'),
        ),
    ]
