# Generated by Django 5.0.1 on 2024-02-21 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0017_alter_student_email'),
        ('teacher_app', '0016_examquestion_answer_exercisequestion_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='得分')),
                ('exam_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='teacher_app.examquestion', verbose_name='考试题')),
                ('exercise_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='teacher_app.exercisequestion', verbose_name='练习题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='student_app.student', verbose_name='学生')),
            ],
        ),
    ]
