# Generated by Django 5.0.1 on 2024-02-23 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0018_score'),
        ('teacher_app', '0016_examquestion_answer_exercisequestion_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_completions', to='teacher_app.exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_question_completions', to='teacher_app.examquestion', verbose_name='考试题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_question_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_completions', to='teacher_app.exercise', verbose_name='练习')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseQuestionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('exercise_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_question_completions', to='teacher_app.exercisequestion', verbose_name='练习题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_question_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
    ]
