# Generated by Django 5.0.1 on 2024-03-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0019_examcompletion_examquestioncompletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to='codeFiles/'),
        ),
        migrations.AddField(
            model_name='student',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='wordFiles/'),
        ),
    ]
