# Generated by Django 5.0.1 on 2024-03-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0020_student_code_file_student_word_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='code_file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='word_file',
        ),
    ]
