# Generated by Django 5.0.1 on 2024-03-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0013_adminexam_adminexamquestion'),
        ('student_app', '0021_remove_student_code_file_remove_student_word_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='adminexam_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='administrator_app.adminexamquestion', verbose_name='Admin考试题'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='得分'),
        ),
    ]
