# Generated by Django 5.0.1 on 2024-03-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0013_adminexam_adminexamquestion'),
        ('student_app', '0022_score_adminexam_question_alter_score_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExamCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('adminexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_completions', to='administrator_app.adminexam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='AdminExamQuestionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('adminexam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_question_completions', to='administrator_app.adminexamquestion', verbose_name='考试题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminexam_question_completions', to='student_app.student', verbose_name='学生')),
            ],
        ),
    ]
