# Generated by Django 5.0.1 on 2024-04-07 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0013_adminexam_adminexamquestion'),
        ('student_app', '0023_adminexamcompletion_adminexamquestioncompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='adminexam_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='administrator_app.adminexamquestion', verbose_name='年级考试题'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登录时间'),
        ),
    ]
